create rails api to send random greetings
saied2035/hello-rails-back-end pull request #1
Opened 2022-07-12 19:30 UTC by saied2035

### Project requirements

 - I created a new Rails API app called 'hello-rails-back-end'.
 - I initialized the project with Git.
 - The project has a Postgres database set up.  
 - I created a table for storing messages and I created 5 different greetings. 
 - I created an API endpoint that selects a random greeting from your table.

Live Demo:
[link](https://sleepy-brook-35791.herokuapp.com/messages)

This is the link to the React app PR:
[link](https://github.com/saied2035/hello-react-front-end/pull/1)

Thanks for reviewing my PR. 😄

2022-07-12 20:06 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @saied2035, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have:- 
1. In the README file for the frontend, provide a link to the Rails API (backend app).
1. In the README file for the backend, you should find a link to the frontend part.

Make sure to add both.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-12 20:29 UTC, Rustamxon7 approved these changes
## Hello @Kamba56👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-12 20:29 UTC, rustam-tolipov commented on db/migrate/20220712084832_create_messages.rb
> +    Message.create(data:'Greeting 5')
- [x] [OPTIONAL] You can put this hard-coded data into seeds.rb file and run `rake db:seed` to generate them, to make your migration folder much cleaner.

2022-07-12 20:29 UTC, rustam-tolipov commented on README.md
> +This project is [MIT](./MIT) licensed.
- [x] [OPTIONAL] I think you just forgot to put MIT license on your project. Kindly include it as well.

2022-07-13 08:13 UTC, saied2035 commented
**@Rustamxon7**  Thanks for reviewing my PR. I appreciate your optional suggestions I did them. Thanks again! 😄

2022-07-13 08:15 UTC, merged